# =============================================================================================================             
# =============================================================================================================   
# =============================================================================================================  
#   █████████                  ███████████ ████                     █████   ███   █████                      
#  ███▒▒▒▒▒███                ▒▒███▒▒▒▒▒▒█▒▒███                    ▒▒███   ▒███  ▒▒███                       
# ▒███    ▒▒▒  █████ ███ █████ ▒███   █ ▒  ▒███   ██████    ███████ ▒███   ▒███   ▒███   ██████   ████████   
# ▒▒█████████ ▒▒███ ▒███▒▒███  ▒███████    ▒███  ▒▒▒▒▒███  ███▒▒███ ▒███   ▒███   ▒███  ▒▒▒▒▒███ ▒▒███▒▒███  
#  ▒▒▒▒▒▒▒▒███ ▒███ ▒███ ▒███  ▒███▒▒▒█    ▒███   ███████ ▒███ ▒███ ▒▒███  █████  ███    ███████  ▒███ ▒▒▒   
#  ███    ▒███ ▒▒███████████   ▒███  ▒     ▒███  ███▒▒███ ▒███ ▒███  ▒▒▒█████▒█████▒    ███▒▒███  ▒███       
# ▒▒█████████   ▒▒████▒████    █████       █████▒▒████████▒▒███████    ▒▒███ ▒▒███     ▒▒████████ █████      
#  ▒▒▒▒▒▒▒▒▒     ▒▒▒▒ ▒▒▒▒    ▒▒▒▒▒       ▒▒▒▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒▒███     ▒▒▒   ▒▒▒       ▒▒▒▒▒▒▒▒ ▒▒▒▒▒       
#                                                          ███ ▒███                                          
#                                                         ▒▒██████                                           
# =============================================================================================================
# =============================================================================================================
# =============================================================================================================   
# developing
flag_war:
  enable: false
  # 1 < radius,default 10
  #  game_radius: 12
  my_coin_name: 'sw_coin'
  # if remind player before flag war game open
  need_remind: true
  # Before flag war game start remind count
  before_start_remind: 10
  # Remind interval
  remind_interval: 30
  # Item using to join flag war
  occupy_item: CRYING_OBSIDIAN
  # Time for occupied a flag war zone.
  occupy_time: 600
  # Flag war game zone radius. default 4
  game_radius: 4

# developing
offer:
  enable: false
  cost_before: true
  tax: 0

# developing
online:
  enable: false
  rewards:
    - type: item
      amount: ['Diamond-5','']
      val: 1
    - type: money
      amount: 888
      val: 2
    - type: rp
      amount: 3000
      val: 4

# Handle Player Click Bank-Item Shop event
bank:
  enable: true
  disable_world: ['kingdom','world_nether','world_the_end']

# Death Drops Item
drop:
  enable: true
  head:
    # When player death drops head,set 1 = 100%,default 0.5 SET 0 TO DISABLE
    probability: 0.5
  steal:
    # When player death drops PlayerInventory's item,set 1 = 100%,default 0.5 SET 0 TO DISABLE
    probability: 0.3
    max: 3

# Give up for now
#money:
#  enable: false
#  def: 0